export const openSaucedlogos = [
  {
    id: 1,
    title: "Orange and White",
    description: "Please use this logo in cases where the full logo (Orange and Black, Full White, Full Black) won’t work.",
    svgLogo: "/brandLogos/full_orange_white.svg",
    pngLogo: "/brandLogos/full_orange_white.png",
    isBlackBG: true,
  },
  {
    id: 2,
    title: "Orange and Black",
    description: "Please use this logo in cases where the full logo (Orange and White, Full White, Full Black) won’t work.",
    svgLogo: "/brandLogos/full_orange_black.svg",
    pngLogo: "/brandLogos/full_orange_black.png",
    isBlackBG: false,
  },
  {
    id: 3,
    title: "Full White",
    description: "Please use this logo in cases where full logo (Orange and White, Orange and Black, Full Black) won’t work.",
    svgLogo: "/brandLogos/full_white.svg",
    pngLogo: "/brandLogos/full_white.png",
    isBlackBG: true,  
  },
  {
    id: 4,
    title: "Full Black",
    description: "Please use this logo in cases where the full logo (Orange and White, Orange and Black, Full White) won’t work.",
    svgLogo: "/brandLogos/full_black.svg",
    pngLogo: "/brandLogos/full_black.png",
    isBlackBG: false,  
  },
  {
    id: 5,
    title: "Orange Slice",
    description: "Please use this logo in cases where slice (White, Black) won't work.",
    svgLogo: "/brandLogos/icon_orange.svg",
    pngLogo: "/brandLogos/icon_orange.png",
    isBlackBG: false,
  },
  {
    id: 6,
    title: "Black Slice",
    description: "Please use this logo in cases where slice (White, Orange) won’t work.",
    svgLogo: "/brandLogos/icon_black.svg",
    pngLogo: "/brandLogos/icon_black.png",
    isBlackBG: false,
  },
  {
    id: 7,
    title: "White Slice",
    description: "Please use this logo in cases where slice (Orange, Black) won’t work.",
    svgLogo: "/brandLogos/icon_white.svg",
    pngLogo: "/brandLogos/icon_white.png",
    isBlackBG: true,
  },
]